const findStoreByZipCode = (zip) => {
  var allStores = [
    {
      zipcode: 33602,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33603,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33605,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33606,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33607,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33609,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33611,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33616,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33621,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33629,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33677,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "South Tampa",
      "db-id": "1001",
    },
    {
      zipcode: 33701,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33702,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33703,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33704,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33705,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33706,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33707,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33708,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33709,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33710,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33711,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33712,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33713,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33714,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33715,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33716,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33733,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33760,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33762,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33770,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33771,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33772,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33773,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33774,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33776,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33777,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33778,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33781,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33782,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33785,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "St. Pete",
      "db-id": "1004",
    },
    {
      zipcode: 33755,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33756,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33759,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33761,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33763,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33764,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33765,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33767,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34652,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34653,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34655,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34660,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34677,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34681,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34683,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34684,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34685,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34688,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34689,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34690,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34691,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34695,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34696,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34698,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33626,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33635,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 34654,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Countryside",
      "db-id": "1003",
    },
    {
      zipcode: 33604,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33610,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33612,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33613,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33614,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33615,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33617,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33618,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33620,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33624,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33625,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33634,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33637,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33556,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33684,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33558,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 34638,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Carrollwood",
      "db-id": "1002",
    },
    {
      zipcode: 33525,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33540,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33541,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33542,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33543,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33544,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33545,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33548,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33549,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33559,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33592,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33647,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 34637,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 34639,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Wesley Chapel",
      "db-id": "1009",
    },
    {
      zipcode: 33510,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33511,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33534,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33547,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33569,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33578,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33579,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33584,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33594,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33596,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33619,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33570,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33572,
      "delivery-days": ["Sunday", "Monday"],
      store: "Brandon",
      "db-id": "1006",
    },
    {
      zipcode: 33563,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33565,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33566,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33567,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33801,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33803,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33805,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33809,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33810,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33811,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33812,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33813,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33815,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 33527,
      "delivery-days": ["Sunday", "Monday"],
      store: "Plant City",
      "db-id": "7100",
    },
    {
      zipcode: 34201,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34202,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34203,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34205,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34207,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34208,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34209,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34210,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34211,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34212,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34215,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34216,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34217,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34218,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34221,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34222,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34228,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34229,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34231,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34232,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34233,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34234,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34235,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34236,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34237,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34238,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34239,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34240,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34241,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34242,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34243,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34281,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 34219,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Boca",
      "db-id": "1104",
    },
    {
      zipcode: 33073,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33426,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33431,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33432,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33433,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33434,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33435,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33436,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33437,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33441,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33442,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33444,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33445,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33446,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33462,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33467,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33472,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33473,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33483,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33484,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33486,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33487,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33496,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33498,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33004,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33008,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33009,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33019,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33020,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33022,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33060,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33062,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33064,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33301,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33304,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33305,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33306,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33308,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33309,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33315,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33316,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33334,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33394,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33021,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33311,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33312,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Ft. Lauderdale",
      "db-id": "1102",
    },
    {
      zipcode: 33023,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33024,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33025,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33026,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33065,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33068,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33071,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33081,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33082,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33083,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33084,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33313,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33314,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33317,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33318,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33319,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33321,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33322,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33323,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33324,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33325,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33326,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33327,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33328,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33330,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33331,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33332,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33351,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33026,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33067,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33076,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33428,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33063,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33066,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33069,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Plantation",
      "db-id": "1101",
    },
    {
      zipcode: 33002,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33010,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33011,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33012,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33013,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33014,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33015,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33016,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33017,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33018,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33054,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33055,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33056,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33101,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33102,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33106,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33111,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33112,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33114,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33122,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33124,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33125,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33126,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33127,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33128,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33129,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33130,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33131,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33132,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33133,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33134,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33135,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33136,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33137,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33138,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33139,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33140,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33141,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33142,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33143,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33144,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33145,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33146,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33147,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33150,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33151,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33152,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33153,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33154,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33155,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33156,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33157,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33158,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33160,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33161,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33162,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33163,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33164,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33165,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33166,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33167,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33168,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33169,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33172,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33173,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33174,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33175,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33176,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33178,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33179,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33180,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33181,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33182,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33183,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33184,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33185,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33186,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33188,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33191,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33192,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33193,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33195,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33198,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33199,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33206,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33222,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33231,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33233,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33234,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33238,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33242,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33243,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33245,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33247,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33255,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33256,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33261,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33265,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33266,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33269,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33280,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33299,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33189,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33196,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33177,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33032,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33027,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33028,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 33029,
      "delivery-days": ["Sunday", "Monday"],
      store: "Miami",
      "db-id": "7003",
    },
    {
      zipcode: 32701,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32707,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32712,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32714,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32730,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32746,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32750,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32751,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32752,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32765,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32771,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32773,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32779,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32789,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32792,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32801,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32803,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32804,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32805,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32806,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32807,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32808,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32810,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32812,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32814,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32816,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32817,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32822,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32825,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32826,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32828,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32829,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32708,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32809,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32703,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Winter Park",
      "db-id": "1202",
    },
    {
      zipcode: 32811,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32818,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32819,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32821,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32824,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32827,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32830,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32835,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32836,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32837,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32839,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 33896,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34734,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34741,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34743,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34744,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34746,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34747,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34756,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34760,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34761,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34786,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34787,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 34771,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 32832,
      "delivery-days": ["Sunday", "Monday", "Tuesday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 33407,
      "delivery-days": ["Sunday"],
      store: "Dr. Phillips",
      "db-id": "1201",
    },
    {
      zipcode: 33418,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33410,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33417,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33404,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33409,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33403,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33401,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33408,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33413,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33415,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33406,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33458,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33405,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33477,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33461,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33463,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33467,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33460,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33462,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33480,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33411,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33414,
      "delivery-days": ["Sunday"],
      store: "West Palm",
      "db-id": "7004",
    },
    {
      zipcode: 33903,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33909,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33917,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33990,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33918,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33901,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33916,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33993,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33905,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33991,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33904,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33919,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33907,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33966,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33914,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33913,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33912,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33971,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33908,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33920,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33973,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33931,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33976,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33967,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33928,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33972,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33936,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33974,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 33965,
      "delivery-days": ["Sunday"],
      store: "Ft. Meyers",
      "db-id": "7005",
    },
    {
      zipcode: 32601,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32609,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32605,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32603,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32612,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32607,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32608,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32641,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32606,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32667,
      "delivery-days": ["Sunday"],
      store: "Gainseville",
      "db-id": "",
    },
    {
      zipcode: 32202,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32206,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32201,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32209,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32204,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32207,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32232,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32203,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32211,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32255,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32208,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32254,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32205,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32277,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32235,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32231,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32247,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32216,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32210,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32218,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32219,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32217,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32236,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32225,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32239,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32246,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32212,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32244,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32245,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32256,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32099,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32257,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32238,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32224,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32214,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32237,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32223,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32241,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32229,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32258,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32233,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32006,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32067,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32250,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32266,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32259,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32227,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32081,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32082,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32260,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 32226,
      "delivery-days": ["Sunday"],
      store: "Jacksonville",
      "db-id": "7008",
    },
    {
      zipcode: 34102,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34104,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34112,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34105,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34106,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34108,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34109,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34119,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34114,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34117,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34110,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34107,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34120,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34134,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34135,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34145,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34133,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34146,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 33928,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 33931,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34136,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 34140,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 33932,
      "delivery-days": ["Sunday"],
      store: "Naples",
      "db-id": "7009",
    },
    {
      zipcode: 30004,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30005,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30009,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30075,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30076,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30114,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30115,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30188,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30189,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30024,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30040,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30097,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30519,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30041,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30518,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30028,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30043,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30067,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30068,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30080,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30305,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30306,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30309,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30319,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30324,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30326,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30327,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30328,
      "delivery-days": ["Sunday"],
    },
    {
      zipcode: 30329,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30338,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30339,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30340,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30341,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30342,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30345,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30346,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30350,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30360,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30004,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30009,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30062,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30066,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30075,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30076,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30102,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30114,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30115,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30144,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30188,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30189,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30005,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30022,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30024,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30040,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30041,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30043,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30044,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30045,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30046,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30047,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30071,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30092,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30093,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30096,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30097,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30518,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30519,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30060,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30021,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30022,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30084,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30033,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30322,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30076,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30308,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
    {
      zipcode: 30126,
      "delivery-days": ["Sunday"],
      store: "Atlanta",
      "db-id": "5001",
    },
  ];

  return allStores.find(({ zipcode }) => zipcode === parseInt(zip));
};

module.exports = findStoreByZipCode;
